### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by VinterNacht** [orlouge/custom-ore-veins#3]
This starts as a question because I am uncertain. It ends as a suggestion in case the answer is no.
Can you define ore generation by biome?
If not, is that a feature we could get?

**Comment by orlouge** [comment]
I don't plan on adding new features to this mod, the closest thing you can do is altering the toggle density function based on the biome noise parameters, there's a comment chain about this on the CurseForge page of the mod.

**Comment by VinterNacht** [comment]
It's unfortunate that you won't be adding new features, but I understand.  Thank you for this tool. :)
